# Generated by Django 4.2.5 on 2023-09-19 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezekielpost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='image',
        ),
    ]
