# Generated by Django 4.2.5 on 2023-10-02 05:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ezekielpost', '0003_department_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='my_field',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
