# Generated by Django 2.2.2 on 2019-09-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezekielpost', '0004_auto_20190929_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='stage',
            field=models.CharField(blank=True, choices=[('Planning', 'Planning'), ('Execution', 'Execution'), ('Optimization', 'Optimization')], max_length=400, null=True),
        ),
    ]
