# Generated by Django 4.2.5 on 2023-10-02 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezekielpost', '0005_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='my_field',
        ),
    ]
