# Generated by Django 2.2.2 on 2019-10-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezekielpost', '0008_casestudies_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudies',
            name='department',
            field=models.ManyToManyField(blank=True, to='ezekielpost.Department'),
        ),
        migrations.AlterField(
            model_name='casestudies',
            name='industry',
            field=models.ManyToManyField(blank=True, to='ezekielpost.Industry'),
        ),
    ]
