# Generated by Django 2.2.2 on 2019-10-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezekielpost', '0009_auto_20191006_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='industry',
            field=models.ManyToManyField(blank=True, to='ezekielpost.Industry'),
        ),
    ]
