# Generated by Django 2.2.2 on 2019-11-06 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezekielpost', '0011_auto_20191106_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='industry',
        ),
        migrations.AddField(
            model_name='post',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ezekielpost.Industry'),
        ),
    ]
