# Generated by Django 2.2.2 on 2019-11-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezekielpost', '0012_auto_20191106_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(blank=True, choices=[('post', 'post'), ('page', 'page'), ('case_studies', 'case_studies'), ('featured', 'featured')], max_length=400, null=True),
        ),
    ]
